server:
  port: 8080
  servlet:
    context-path: /interviewApp

spring:
  main:
    banner-mode: off
  application:
    name: interviewApp
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: interview_app
    open-in-view: false

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha

  datasource:
    url: jdbc:postgresql://localhost:5432/interview_app?useSSL=false
    username: bestuser
    password: admin

  liquibase:
      change-log: classpath:db/changelog/changelog-master.xml
      enabled: true
      default-schema: interview_app

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

jwt:
  secret: MySuperSecretKeyForJWTThatIsLongEnoughAndSecureForHS512Algorithm
  expiration: 3600000
  refresh-expiration: 86400000